### ISSUE TITLE
Error non-zero exit status 2

### ISSUE THREAD

**Issue by alexfoias** [UNFmontreal/Dcm2Bids#139]
Hi,

I have tried to run dcm2bids for a dataset, but I got some errors.

Here is my output:

<Details>

```
[10/09/21 3:57:25] (base) alex@NeuroPoly-MacBook-Pro Desktop % ls /Users/alex/data/data_ucsf/5416/5416_T1/
/Users/alex/data/data_ucsf/5416/5416_T1/
IM-0001-0001.dcm IM-0001-0002.dcm IM-0001-0003.dcm IM-0001-0004.dcm IM-0001-0005.dcm IM-0001-0006.dcm IM-0001-0007.dcm IM-0001-0008.dcm IM-0001-0009.dcm IM-0001-0010.dcm IM-0001-0011.dcm IM-0001-0012.dcm
[10/09/21 3:58:01] (base) alex@NeuroPoly-MacBook-Pro Desktop % dcm2bids -d /Users/alex/data/data_ucsf/5416/5416_T1/ -p sub-5416 -c /Users/alex/code/spine_config.txt

INFO:dcm2bids.dcm2bids:--- dcm2bids start ---
INFO:dcm2bids.dcm2bids:OS:version: macOS-10.16-x86_64-i386-64bit
INFO:dcm2bids.dcm2bids:python:version: 3.8.3 (default, May 19 2020, 13:54:14) [Clang 10.0.0 ]
INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.6
INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20210317
INFO:dcm2bids.dcm2bids:participant: sub-5416
INFO:dcm2bids.dcm2bids:session: 
INFO:dcm2bids.dcm2bids:config: /Users/alex/code/spine_config.txt
INFO:dcm2bids.dcm2bids:BIDS directory: /Users/alex/Desktop
INFO:dcm2bids.utils:Running dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /Users/alex/Desktop/tmp_dcm2bids/sub-5416 /Users/alex/data/data_ucsf/5416/5416_T1/
Traceback (most recent call last):
  File "/Users/alex/miniconda3/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/Users/alex/miniconda3/lib/python3.8/site-packages/dcm2bids/dcm2bids.py", line 291, in main
    return app.run()
  File "/Users/alex/miniconda3/lib/python3.8/site-packages/dcm2bids/dcm2bids.py", line 120, in run
    dcm2niix.run(self.forceDcm2niix)
  File "/Users/alex/miniconda3/lib/python3.8/site-packages/dcm2bids/dcm2niix.py", line 90, in run
    self.execute()
  File "/Users/alex/miniconda3/lib/python3.8/site-packages/dcm2bids/dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "/Users/alex/miniconda3/lib/python3.8/site-packages/dcm2bids/utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/Users/alex/miniconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/alex/miniconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', '/Users/alex/Desktop/tmp_dcm2bids/sub-5416', '/Users/alex/data/data_ucsf/5416/5416_T1/']' returned non-zero exit status 2.
```

</Details>

Here is my config for dcm2bids and dcm2niix:

<Details>

```
[10/09/21 3:59:38] (base) alex@NeuroPoly-MacBook-Pro Desktop % dcm2bids -h

usage: dcm2bids [-h] -d DICOM_DIR [DICOM_DIR ...] -p PARTICIPANT [-s SESSION] -c CONFIG [-o OUTPUT_DIR] [--forceDcm2niix] [--clobber] [-l {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [-a]

Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure
dcm2bids 2.1.6

optional arguments:
  -h, --help            show this help message and exit
  -d DICOM_DIR [DICOM_DIR ...], --dicom_dir DICOM_DIR [DICOM_DIR ...]
                        DICOM directory(ies)
  -p PARTICIPANT, --participant PARTICIPANT
                        Participant ID
  -s SESSION, --session SESSION
                        Session ID
  -c CONFIG, --config CONFIG
                        JSON configuration file (see example/config.json)
  -o OUTPUT_DIR, --output_dir OUTPUT_DIR
                        Output BIDS directory, Default: current directory (/Users/alex/Desktop)
  --forceDcm2niix       Overwrite previous temporary dcm2niix output if it exists
  --clobber             Overwrite output if it exists
  -l {DEBUG,INFO,WARNING,ERROR,CRITICAL}, --log_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set logging level
  -a, --anonymizer      This option no longer exists from the script in this release. See:https://github.com/unfmontreal/Dcm2Bids/blob/master/README.md#defaceTpl

            Documentation at https://github.com/unfmontreal/Dcm2Bids
            
[10/09/21 3:59:42] (base) alex@NeuroPoly-MacBook-Pro Desktop % dcm2niix -h

Chris Rorden's dcm2niiX version v1.0.20210317  Clang12.0.0 x86-64 (64-bit MacOS)
usage: dcm2niix [options] <in_folder>
 Options :
  -1..-9 : gz compression level (1=fastest..9=smallest, default 6)
  -a : adjacent DICOMs (images from same series always in same folder) for faster conversion (n/y, default n)
  -b : BIDS sidecar (y/n/o [o=only: no NIfTI], default y)
   -ba : anonymize BIDS (y/n, default y)
  -c : comment stored in NIfTI aux_file (provide up to 24 characters e.g. '-c first_visit')
  -d : directory search depth. Convert DICOMs in sub-folders of in_folder? (0..9, default 5)
  -e : export as NRRD instead of NIfTI (y/n, default n)
  -f : filename (%a=antenna (coil) name, %b=basename, %c=comments, %d=description, %e=echo number, %f=folder name, %g=accession number, %i=ID of patient, %j=seriesInstanceUID, %k=studyInstanceUID, %m=manufacturer, %n=name of patient, %o=mediaObjectInstanceUID, %p=protocol, %r=instance number, %s=series number, %t=time, %u=acquisition number, %v=vendor, %x=study ID; %z=sequence name; default '%f_%p_%t_%s')
  -g : generate defaults file (y/n/o/i [o=only: reset and write defaults; i=ignore: reset defaults], default n)
  -h : show help
  -i : ignore derived, localizer and 2D images (y/n, default n)
  -l : losslessly scale 16-bit integers to use dynamic range (y/n/o [yes=scale, no=no, but uint16->int16, o=original], default n)
  -m : merge 2D slices from same series regardless of echo, exposure, etc. (n/y or 0/1/2, default 2) [no, yes, auto]
  -n : only convert this series CRC number - can be used up to 16 times (default convert all)
  -o : output directory (omit to save to input folder)
  -p : Philips precise float (not display) scaling (y/n, default y)
  -r : rename instead of convert DICOMs (y/n, default n)
  -s : single file mode, do not convert other images in folder (y/n, default n)
  -u : up-to-date check
  -v : verbose (n/y or 0/1/2, default 0) [no, yes, logorrheic]
  -w : write behavior for name conflicts (0,1,2, default 2: 0=skip duplicates, 1=overwrite, 2=add suffix)
  -x : crop 3D acquisitions (y/n/i, default n, use 'i'gnore to neither crop nor rotate 3D acquistions)
  -z : gz compress images (y/o/i/n/3, default n) [y=pigz, o=optimal pigz, i=internal:miniz, n=no, 3=no,3D]
  --big-endian : byte order (y/n/o, default o) [y=big-end, n=little-end, o=optimal/native]
  --progress : Slicer format progress information (y/n, default n)
  --terse : omit filename post-fixes (can cause overwrites)
  --version : report version
  --xml : Slicer format features
 Defaults file : /Users/alex/.dcm2nii.ini
 Examples :
  dcm2niix /Users/chris/dir
  dcm2niix -c "my comment" /Users/chris/dir
  dcm2niix -o /users/cr/outdir/ -z y ~/dicomdir
  dcm2niix -f %p_%s -b y -ba n ~/dicomdir
  dcm2niix -f mystudy%s ~/dicomdir
  dcm2niix -o "~/dir with spaces/dir" ~/dicomdir
Example output filename: 'myFolder_MPRAGE_19770703150928_1.nii'

```

</Details>

I use the config file from spine-generic: https://github.com/spine-generic/spine-generic/blob/master/config_spine.txt

Thanks for your help.

**Comment by alexfoias** [comment]
I have even tried on Ubuntu 20.04.3 LTS. The problem seems to persist.

<Details>

```
(dcm2bids) alfoi_admin@tristano:~/code$ ls  ~/data/data_ucsf/5416/5416_T1/
IM-0001-0001.dcm  IM-0001-0003.dcm  IM-0001-0005.dcm  IM-0001-0007.dcm  IM-0001-0009.dcm  IM-0001-0011.dcm
IM-0001-0002.dcm  IM-0001-0004.dcm  IM-0001-0006.dcm  IM-0001-0008.dcm  IM-0001-0010.dcm  IM-0001-0012.dcm
(dcm2bids) alfoi_admin@tristano:~/code$ dcm2bids -d ~/data/data_ucsf/5416/5416_T1/ -p sub-5416 -c ~/code/spine_config.txt 
INFO:dcm2bids.dcm2bids:--- dcm2bids start ---
INFO:dcm2bids.dcm2bids:OS:version: Linux-5.11.0-34-generic-x86_64-with-glibc2.31
INFO:dcm2bids.dcm2bids:python:version: 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:34) [GCC 9.4.0]
INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.6
INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20210317
INFO:dcm2bids.dcm2bids:participant: sub-5416
INFO:dcm2bids.dcm2bids:session: 
INFO:dcm2bids.dcm2bids:config: /home/alfoi_admin/code/spine_config.txt
INFO:dcm2bids.dcm2bids:BIDS directory: /home/alfoi_admin/code
INFO:dcm2bids.utils:Running dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /home/alfoi_admin/code/tmp_dcm2bids/sub-5416 /home/alfoi_admin/data/data_ucsf/5416/5416_T1/
Traceback (most recent call last):
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/bin/dcm2bids", line 10, in <module>
    sys.exit(main())
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/site-packages/dcm2bids/dcm2bids.py", line 291, in main
    return app.run()
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/site-packages/dcm2bids/dcm2bids.py", line 120, in run
    dcm2niix.run(self.forceDcm2niix)
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/site-packages/dcm2bids/dcm2niix.py", line 90, in run
    self.execute()
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/site-packages/dcm2bids/dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/site-packages/dcm2bids/utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/alfoi_admin/miniconda3/envs/dcm2bids/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', '/home/alfoi_admin/code/tmp_dcm2bids/sub-5416', '/home/alfoi_admin/data/data_ucsf/5416/5416_T1/']' returned non-zero exit status 2.
```

</Details>

**Comment by arnaudbore** [comment]
You've got an issue with the dcm2niix conversion. Try to run dcm2niix you should see an error coming from the converter.

**Comment by alexfoias** [comment]
Hi @arnaudbore ,

Yes, indeed there seems to be a problem with the converter:

```
(dcm2bids) alfoi_admin@tristano:~/data/data_ucsf/5416/5416_T1$ dcm2niix .
Compression will be faster with 'pigz' installed
Chris Rorden's dcm2niiX version v1.0.20210317  GCC9.3.0 x86-64 (64-bit Linux)
Found 12 DICOM file(s)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
No valid DICOM images were found
```

I think is linked to this https://neurostars.org/t/unsupported-transfer-syntex-when-using-dcm2niix/6089/6 

How should I configure `dcm2bids` to work ? I used https://unfmontreal.github.io/Dcm2Bids/docs/2-tutorial/#setup for setting up the env.

**Comment by arnaudbore** [comment]
dcm2niix installation is missing from this tutorial. The version you have seems to be broken or at least does not work. Please follow neurostars advices to install dcm2niix correctly.

**Comment by alexfoias** [comment]
okay, I have installed the proper dcm2niix necessary for the platform. Now everything seems to work.

Maybe an output saying check the dependencies may help users in the future.

We can close the issue.
