### ISSUE TITLE
Issue with dcm2bids_helper: No such file or directory: 'dcm2niix'

### ISSUE THREAD

**Issue by aftmnelbier11** [UNFmontreal/Dcm2Bids#140]
I am using Ubuntu 20.4. I have dicom files in the sourcedata folder. My directory is set to the sourcedata folder. The path is as such `sourcedata > P04 > task1/task2/fieldmaps > dicom files` I am running `dcm2bids_helper -d P04/`.

I continue to get this error:
Traceback (most recent call last):
  File "/usr/local/bin/dcm2bids_helper", line 8, in <module>
    sys.exit(main())
  File "/home/nevia-admin/.local/lib/python3.8/site-packages/dcm2bids/helper.py", line 42, in main
    rsl = app.run()
  File "/home/nevia-admin/.local/lib/python3.8/site-packages/dcm2bids/dcm2niix.py", line 90, in run
    self.execute()
  File "/home/nevia-admin/.local/lib/python3.8/site-packages/dcm2bids/dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "/home/nevia-admin/.local/lib/python3.8/site-packages/dcm2bids/utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dcm2niix'

I have ran this exact command in this exact way on multiple different Ubuntu systems on different computers and never got this error. Any ideas?

**Comment by arnaudbore** [comment]
Please make sure dcm2niix is installed on your computer. You can get it using this link [dcm2niix](https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20211006/dcm2niix_lnx.zip).
