### ISSUE TITLE
dcm2bids_helper issue in tutorial

### ISSUE THREAD

**Issue by andrew-yian-sun** [UNFmontreal/Dcm2Bids#146]
I am going through the dcm2bids tutorial. Everything is going smoothly until the "Dicom to Nifti Conversion" section.
I run the follow code as shown: `dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In/`, but I receive an "Output folder invalid" error message. The `tmp_dcm2bids/helper` directory is created but no nifti files are present.

Below is the code I ran, along with the full error message:
`(dcm2bids) C:\Users\Andrew\BIDS_testing\dcm2bids_test>dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In/`
```Error: Output folder invalid: C:UsersAndrewBIDS_testingdcm2bids_testtmp_dcm2bidshelper
Traceback (most recent call last):
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\Scripts\dcm2bids_helper-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\helper.py", line 42, in main
    rsl = app.run()
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 90, in run
    self.execute()
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', 'C:UsersAndrewBIDS_testingdcm2bids_testtmp_dcm2bidshelper', 'sourcedata/dcm_qa_nih-master/In/']' returned non-zero exit status 6.```

**Comment by ysl16** [comment]
I came across exactly the same thing. Not sure if this is the reason, but it seems that the program could not convert the "\" in the path of the Windows system to "/"?  

This was my error message:
```
(dcm2bids) c:\Users\yslin\Documents\dcm2bids-tutorial>dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In
Error: Output folder invalid: c:UsersyslinDocumentsdcm2bids-tutorialtmp_dcm2bidshelper
Traceback (most recent call last):
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\Scripts\dcm2bids_helper-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\helper.py", line 42, in main
    rsl = app.run()
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 90, in run
    self.execute()
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\yslin\anaconda3\envs\dcm2bids\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', 'c:UsersyslinDocumentsdcm2bids-tutorialtmp_dcm2bidshelper', 'sourcedata/dcm_qa_nih-master/In']' returned non-zero exit status 6.
```

**Comment by keiichiiownsu12** [comment]
Try appending `-o .\` or `-o ./` to your `dcm2bids_helper` call, e.g.:
`(dcm2bids) C:\Users\Andrew\BIDS_testing\dcm2bids_test>dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In/ -o ./`

**Comment by andrew-yian-sun** [comment]
Hi @keiichiiownsu12, unfortunately trying both `-o .\` or `-o ./` to your `dcm2bids_helper` call seemed to have resulted in the output folder being invalid:

```
(dcm2bids) C:\Users\Andrew\BIDS_testing\dcm2bids_test>dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In/ -o ./
Error: Output folder invalid: ./tmp_dcm2bidshelper
Traceback (most recent call last):
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\Scripts\dcm2bids_helper-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\helper.py", line 42, in main
    rsl = app.run()
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 90, in run
    self.execute()
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', './tmp_dcm2bidshelper', 'sourcedata/dcm_qa_nih-master/In/']' returned non-zero exit status 6.
```

```
(dcm2bids) C:\Users\Andrew\BIDS_testing\dcm2bids_test>dcm2bids_helper -d sourcedata/dcm_qa_nih-master/In/ -o .\
Error: Output folder invalid: .tmp_dcm2bidshelper
Traceback (most recent call last):
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\Scripts\dcm2bids_helper-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\helper.py", line 42, in main
    rsl = app.run()
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 90, in run
    self.execute()
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\dcm2niix.py", line 100, in execute
    output = run_shell_command(cmd)
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\site-packages\dcm2bids\utils.py", line 113, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Andrew\anaconda3\envs\dcm2bids\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', '.tmp_dcm2bidshelper', 'sourcedata/dcm_qa_nih-master/In/']' returned non-zero exit status 6.
```

**Comment by arnaudbore** [comment]
@andrew-yian-sun @ysl16 @keiichiiownsu12 we updated the [documentation](https://unfmontreal.github.io/Dcm2Bids/) and we have a PR (#158) that should fix your issue.
Can you give it a try ? Feedbacks will be also appreciated. 
Thank you in advance.
