### ISSUE TITLE
KeyError: 'datatype'

### ISSUE THREAD

**Issue by JunhongYu** [UNFmontreal/Dcm2Bids#279]
Hi there, i'm attaching my config file here [dcm2bids_config.json](https://github.com/UNFmontreal/Dcm2Bids/files/12904416/dcm2bids_config.json) not sure if this is related to my config file?  

```
WARNING | Previous dcm2bids temporary directory output found:
WARNING | /home/junhong.yu/PGMH/bids/tmp_dcm2bids/sub-0064
WARNING | 'force' argument is set to True
WARNING | Cleaning the previous directory and running dcm2bids
INFO    | Running: dcm2niix -b y -ba y -z y -f %3s_%f_%p_%t -o /home/junhong.yu/PGMH/bids/tmp_dcm2bids/sub-0064 sourcedata/GEMH_0064
INFO    | Check log file for dcm2niix output

INFO    | SIDECAR PAIRING
INFO    | No Pairing  <-  001_GEMH_0064_AAHead_Scout_20230918121533
INFO    | No Pairing  <-  002_GEMH_0064_AAHead_Scout_20230918121533_i00001
INFO    | No Pairing  <-  002_GEMH_0064_AAHead_Scout_20230918121533_i00002
INFO    | No Pairing  <-  002_GEMH_0064_AAHead_Scout_20230918121533_i00003
INFO    | No Pairing  <-  002_GEMH_0064_AAHead_Scout_20230918121533_i00004
INFO    | No Pairing  <-  003_GEMH_0064_AAHead_Scout_20230918121533_i00001
INFO    | No Pairing  <-  003_GEMH_0064_AAHead_Scout_20230918121533_i00002
INFO    | No Pairing  <-  003_GEMH_0064_AAHead_Scout_20230918121533_i00003
INFO    | No Pairing  <-  004_GEMH_0064_AAHead_Scout_20230918121533_i00001
INFO    | No Pairing  <-  004_GEMH_0064_AAHead_Scout_20230918121533_i00002
INFO    | No Pairing  <-  004_GEMH_0064_AAHead_Scout_20230918121533_i00003
Traceback (most recent call last):
  File "/home/junhong.yu/dcm2bids/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/home/junhong.yu/dcm2bids/lib/python3.7/site-packages/dcm2bids/cli/dcm2bids.py", line 125, in main
    app = Dcm2BidsGen(**vars(args)).run()
  File "/home/junhong.yu/dcm2bids/lib/python3.7/site-packages/dcm2bids/dcm2bids_gen.py", line 108, in run
    parser.build_acquisitions(self.participant)
  File "/home/junhong.yu/dcm2bids/lib/python3.7/site-packages/dcm2bids/sidecar.py", line 395, in build_acquisitions
    desc, sidecar = self.searchDcmTagEntity(sidecar, desc)
  File "/home/junhong.yu/dcm2bids/lib/python3.7/site-packages/dcm2bids/sidecar.py", line 468, in searchDcmTagEntity
    auto_acq = '_'.join([descWithTask['datatype'], descWithTask["suffix"]])
KeyError: 'datatype'

```

**Comment by arnaudbore** [comment]
Dear @GerardYu ,

You are using dcm2bids >= 3.x.
Please follow these instructions to modify your config file accordingly: https://unfmontreal.github.io/Dcm2Bids/3.1.1/upgrade/#upgrading-from-2x-to-3x

We also highly suggest people to post their issues on https://neurostars.org/ using the dcm2bids tag.
There are even more people able to help you on this forum than here on github.

If you have any questions, please post them there.

Best,
Arnaud
