### ISSUE TITLE
`skip_dcm2niix` fails if dcm2niix is not in $PATH

### ISSUE THREAD

**Issue by SamGuay** [UNFmontreal/Dcm2Bids#320]
I had to reorganize a bunch of nii/json on an HPC so I used the binaries. Worked well until I wanted to skip dcm2niix since it is not installed. The error message is somewhat misleading considering the `skip_dcm2niix` command. It is brought up because of  `dcm2niix_version`.

Ideally if dcm2niix is skipped, it should not be required at all.

```
[user@machine]$ ./dcm2bids --auto_extract_entities -d sub-101 -c /output/code/config.json -p 101 --skip_dcm2niix
INFO    | --- dcm2bids start ---
INFO    | Running the following command: ../dcm2bids --auto_extract_entities -d sub-101 -c code/config.json -p 101 --skip_dcm2niix
INFO    | OS version: Linux-4.18.0-553.16.1.el8_10.x86_64-x86_64-AMD_EPYC_7532_32-Core_Processor-with-glibc2.37
INFO    | Python version: 3.11.2 (main, Feb 22 2023, 16:33:54) [GCC 11.3.0]
INFO    | dcm2bids version: 3.2.0
ERROR   | dcm2niix is not in your PATH or not installed.
ERROR   | https://github.com/rordenlab/dcm2niix to troubleshoot.
Traceback (most recent call last):
  File "/tmp/onefile_2830864_1728529180_152005/dcm2bids.py", line 144, in <module>
  File "/tmp/onefile_2830864_1728529180_152005/dcm2bids.py", line 120, in main
  File "/tmp/onefile_2830864_1728529180_152005/dcm2bids/utils/tools.py", line 105, in dcm2niix_version
FileNotFoundError: dcm2niix is not in your PATH or not installed. -> https://github.com/rordenlab/dcm2niix to troubleshoot.
```

**Comment by arnaudbore** [comment]
Will be fixed by the end of next week!

**Comment by arnaudbore** [comment]
fixed in dev
