### ISSUE TITLE
apptainer / singularity version requirement

### ISSUE THREAD

**Issue by celstark** [UNFmontreal/Dcm2Bids#323]
Running your container in apptainer 1.3.4 is just fine.  Running it in 1.2.5 (or older versions of singularity) gives the following:
```
apptainer --version
apptainer version 1.2.5-1.el9

apptainer exec code/dcm2bids_3.2.0.sif dcm2bids --help
Traceback (most recent call last):
  File "/venv/bin/dcm2bids", line 5, in <module>
    from dcm2bids.cli.dcm2bids import main
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "/venv/lib/python3.12/site-packages/__editable___dcm2bids_3_2_0_finder.py", line 20, in find_spec
    return cls._find_spec(fullname, Path(pkg_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/__editable___dcm2bids_3_2_0_finder.py", line 38, in _find_spec
    if candidate.exists():
       ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/pathlib.py", line 860, in exists
    self.stat(follow_symlinks=follow_symlinks)
  File "/venv/lib/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dcm2bids/dcm2bids/__init__.py'
```

The prior 3.1.0 though was fine:
```
apptainer exec code/dcm2bids_3.1.0.sif dcm2bids --help
usage: dcm2bids [-h] -d DICOM_DIR [DICOM_DIR ...] -p PARTICIPANT [-s SESSION] -c CONFIG [-o OUTPUT_DIR] [--auto_extract_entities] [--bids_validate]
                [--force_dcm2bids] [--skip_dcm2niix] [--clobber] [-l {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [-v]

Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure

options:
  -h, --help            show this help message and exit
...
```

Note, it does run in the newer apptainer:
```
apptainer --version
apptainer version 1.3.4-1.el9

apptainer exec code/dcm2bids_3.1.0.sif dcm2bids --help
usage: dcm2bids [-h] -d DICOM_DIR [DICOM_DIR ...] -p PARTICIPANT [-s SESSION] -c CONFIG [-o OUTPUT_DIR] [--auto_extract_entities] [--bids_validate]
                [--force_dcm2bids] [--skip_dcm2niix] [--clobber] [-l {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [-v]

Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure

options:
  -h, --help            show this help message and exit
...
```

**Comment by arnaudbore** [comment]
Thank you for the issue. I will check if I can make it work otherwise I will need to tell people to update apptainer.

**Comment by ColleenHughes** [comment]
Hi, I am seeing a similar error using apptainer 1.3.6 FYI. Python install works fine, which is fine for my purpose. 

`
[collhugh@i65 cont_imgs]$ apptainer run dcm2bids_3.2.0.sif --help 
INFO:    gocryptfs not found, will not be able to use gocryptfs
Traceback (most recent call last):
  File "/venv/bin/dcm2bids", line 5, in <module>
    from dcm2bids.cli.dcm2bids import main
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "/venv/lib/python3.12/site-packages/__editable___dcm2bids_3_2_0_finder.py", line 20, in find_spec
    return cls._find_spec(fullname, Path(pkg_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/__editable___dcm2bids_3_2_0_finder.py", line 38, in _find_spec
    if candidate.exists():
       ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/pathlib.py", line 860, in exists
    self.stat(follow_symlinks=follow_symlinks)
  File "/venv/lib/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dcm2bids/dcm2bids/__init__.py'
`

**Comment by SamGuay** [comment]
I have a simple hunch for this issue — can you try to run it with these flags?

`apptainer run -e --containall --no-home dcm2bids_3.2.0.sif --help`

The `-e` (`--cleanenv`) flag prevents host environment variables from leaking into the container, and `--containall` (and  optionally `--no-home`, which avoids mounting your home directory) might be masking or conflicting with internal paths in the container vs your host. 

I had this error once running another container and solved it this way so hopefully it will clear up the permission error!

https://unfmontreal.github.io/Dcm2Bids/3.2.0/how-to/container/ has the `-e and --containall` options specified so that might be a reason why we never encountered this issue in the past 🤔

**Comment by arnaudbore** [comment]
Time flies, I feel like there is enough info here people can find if they got into this issue and nowadays apptainer is pretty much everywhere. Let's close this one 👍
