### ISSUE TITLE
dcm2bids_helper can't deal with spaces in directory names

### ISSUE THREAD

**Issue by dmd** [UNFmontreal/Dcm2Bids#64]
dcm2bids_helper fails if the folder name given has spaces in it, even if those spaces are escaped.

**Comment by dmd** [comment]
```
$ dcm2bids_helper -d sourcedata/Russell_William/Investigators_Frederick_R01_Cvr_20180306\ -\ 105ggu53pc/
Error: Unable to find any DICOM images in 105ggu53pc (or subfolders 5 deep)
Traceback (most recent call last):
  File "/usr/local/bin/dcm2bids_helper", line 51, in <module>
    sys.exit(main())
  File "/usr/local/bin/dcm2bids_helper", line 44, in main
    rsl = app.run()
  File "/usr/local/lib/python2.7/site-packages/dcm2bids/dcm2niix.py", line 91, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/dcm2bids/dcm2niix.py", line 104, in execute
    output = run_shell_command(cmd)
  File "/usr/local/lib/python2.7/site-packages/dcm2bids/utils.py", line 109, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', '/Users/ddrucker/2bidsdcm/tmp_dcm2bids/helper', 'sourcedata/Russell_William/Investigators_Frederick_R01_Cvr_20180306', '-', '105ggu53pc/']' returned non-zero exit status 2
```

**Comment by pn2200** [comment]
`dcm2bids_helper` uses [Python's shlex](https://docs.python.org/3/library/shlex.html) package to parse arguments passed to `dcm2niix`, and it seems to require using quotes around arguments that have escape sequences, so the appropriate command line would be:

```
dcm2bids_helper -d "sourcedata/Russell_William/Investigators_Frederick_R01_Cvr_20180306\ -\ 105ggu53pc/"
```

**Comment by arnaudbore** [comment]
Dear @pn2200  and @dmd ,

Thank you @pn2200 for your help. I hope @dmd this fixed your issue.
We are starting a [2021 initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108) don't hesitate if you want to suggest new features.
