### ISSUE TITLE
dcm2bids get dcm2niix error but dcm2niix succed

### ISSUE THREAD

**Issue by asqwerty666** [UNFmontreal/Dcm2Bids#75]
I'm trying to use dcm2bids to do a bulk conversion. I can successfully launch the tool to convert all the participants but I get errors from dcm2niix.

This I got from the logs,

```
INFO:dcm2bids.dcm2bids:--- dcm2bids start ---
INFO:dcm2bids.dcm2bids:OS:version: Linux-3.10.0-514.26.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
INFO:dcm2bids.dcm2bids:python:version: 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
INFO:dcm2bids.dcm2bids:dcm2bids:version: 2.1.4
INFO:dcm2bids.dcm2bids:dcm2niix:version: v1.0.20190902
INFO:dcm2bids.dcm2bids:participant: sub-0009
INFO:dcm2bids.dcm2bids:session:
INFO:dcm2bids.dcm2bids:config: /home/data/facehbi/bids/conversion.json
INFO:dcm2bids.dcm2bids:BIDS directory: /home/data/facehbi/bids
INFO:dcm2bids.utils:Running dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009 /nas/corachan/facehbi//F009/
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.
Traceback (most recent call last):
  File "/usr/local/bin/dcm2bids", line 114, in <module>
    sys.exit(main())
  File "/usr/local/bin/dcm2bids", line 110, in main
    return app.run()
  File "/usr/local/lib/python3.6/site-packages/dcm2bids/dcm2bids.py", line 103, in run
    dcm2niix.run(self.forceDcm2niix)
  File "/usr/local/lib/python3.6/site-packages/dcm2bids/dcm2niix.py", line 91, in run
    self.execute()
  File "/usr/local/lib/python3.6/site-packages/dcm2bids/dcm2niix.py", line 104, in execute
    output = run_shell_command(cmd)
  File "/usr/local/lib/python3.6/site-packages/dcm2bids/utils.py", line 109, in run_shell_command
    return check_output(shlex.split(commandLine))
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dcm2niix', '-b', 'y', '-ba', 'y', '-z', 'y', '-f', '%3s_%f_%p_%t', '-o', '/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009', '/nas/corachan/facehbi//F009/']
' returned non-zero exit status 1.
srun: error: brick02: task 0: Exited with exit code 1
```
I launch th dcm2niix command,
```
[osotolongo@detritus facehbi]$ dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009 /nas/corachan/facehbi//F009/
Chris Rorden's dcm2niiX version v1.0.20190902  GCC4.4.7 (64-bit Linux)
Found 5457 DICOM file(s)
Warning: interpolated protocol 'ep2d_diff_3scan_trace_p2' may be unsuitable for dwidenoise/mrdegibbs. /nas/corachan/facehbi//F009/Serie(13)/Img00001.dcm
Warning: interpolated protocol 'ep2d_diff_3scan_trace_p2' may be unsuitable for dwidenoise/mrdegibbs. /nas/corachan/facehbi//F009/Serie(14)/Img00001.dcm
Warning: interpolated protocol 'ep2d_diff_3scan_trace_p2' may be unsuitable for dwidenoise/mrdegibbs. /nas/corachan/facehbi//F009/Serie(15)/Img00001.dcm
Slices not stacked: echo varies (TE 11, 95; echo 1, 2). Use 'merge 2D slices' option to force stacking
Convert 25 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/010_F009_pd+t2_tse_tra_p2_320_4mm_20150110171319_e1a (260x320x25x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/010_F009_pd+t2_tse_tra_p2_320_4mm_20150110171319_e1a.nii"
Convert 25 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/010_F009_pd+t2_tse_tra_p2_320_4mm_20150110171319_e2a (260x320x25x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/010_F009_pd+t2_tse_tra_p2_320_4mm_20150110171319_e2a.nii"
Convert 25 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/011_F009_t2_fl2d_tra_4mm_hemo_20150110171319a (260x320x25x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/011_F009_t2_fl2d_tra_4mm_hemo_20150110171319a.nii"
Slice positions repeated, but number of slices (4508) not divisible by number of repeats (105): missing images?
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 105 times
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.
Slices not stacked: orientation varies (vNav or localizer?) [-0.0378781 0.940702 0.337112 0.0763953 0.339092 -0.937646] != [0.503175 0.742825 0.441618 0.101769 0.456533 -0.883867]
Convert 2 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00001a (162x162x2x1)
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00001a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00002a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00002a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00003a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00003a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00004a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/002_F009_AAHead_Scout_20150110171319_i00004a.nii"
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/008_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a (256x256x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/008_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a.nii"
Convert 176 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/009_F009_t2_spc_flair_sag_p2_iso_1.0_20150110171319a (252x256x176x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/009_F009_t2_spc_flair_sag_p2_iso_1.0_20150110171319a.nii"
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/016_F009_ep2d_diff_mddw_64_p2_20150110171319a (128x128x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/016_F009_ep2d_diff_mddw_64_p2_20150110171319a.nii"
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Warning: Volume 2 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 60 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/012_F009_ep2d_diff_3scan_trace_p2_20150110171319a (384x384x20x3)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/012_F009_ep2d_diff_3scan_trace_p2_20150110171319a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/004_F009_AAHead_Scout_20150110171319_i00001a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/004_F009_AAHead_Scout_20150110171319_i00002a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/004_F009_AAHead_Scout_20150110171319_i00003a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/004_F009_AAHead_Scout_20150110171319_i00003a.nii"
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Volume 0 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/014_F009_ep2d_diff_3scan_trace_p2_20150110171319a (384x384x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/014_F009_ep2d_diff_3scan_trace_p2_20150110171319a.nii"
Convert 176 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/005_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a (256x256x176x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/005_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a.nii"
Convert 128 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/001_F009_AAHead_Scout_20150110171319a (160x160x128x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/001_F009_AAHead_Scout_20150110171319a.nii"
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/018_F009_ep2d_diff_mddw_64_p2_20150110171319a (128x128x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/018_F009_ep2d_diff_mddw_64_p2_20150110171319a.nii"
Convert 143 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/015_F009_ep2d_diff_mddw_64_p2_20150110171319a (128x128x20x143)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/015_F009_ep2d_diff_mddw_64_p2_20150110171319a.nii"
Warning: Siemens MoCo? Bogus slice timing (range -1..-1, TR=0 seconds)
Unable to determine spatial orientation: 0020,0037 missing (probably not a problem: derived image)
Warning: Unable to determine slice direction: please check whether slices are flipped (derived image)
Warning: Bogus spatial matrix (perhaps non-spatial image): inspect spatial orientation
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/019_F009_ep2d_diff_mddw_64_p2_20150110171319a (128x128x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/019_F009_ep2d_diff_mddw_64_p2_20150110171319a.nii"
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/006_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a (256x256x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/006_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a.nii"
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/007_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a (256x256x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/007_F009_t1_mprage_sag_p2_iso_1.0_20150110171319a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/003_F009_AAHead_Scout_20150110171319_i00001a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/003_F009_AAHead_Scout_20150110171319_i00001a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/003_F009_AAHead_Scout_20150110171319_i00002a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/003_F009_AAHead_Scout_20150110171319_i00002a.nii"
Convert 1 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/003_F009_AAHead_Scout_20150110171319_i00003a (162x162x1x1)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/003_F009_AAHead_Scout_20150110171319_i00003a.nii"
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Volume 0 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/017_F009_ep2d_diff_mddw_64_p2_20150110171319a (128x128x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/017_F009_ep2d_diff_mddw_64_p2_20150110171319a.nii"
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Volume 0 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 20 DICOM as /nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/013_F009_ep2d_diff_3scan_trace_p2_20150110171319a (384x384x20x1)
Compress: "/usr/local/mricron/pigz_mricron" -b 960 -n -f -6 "/nas/data/facehbi/bids/tmp_dcm2bids/sub-0009/013_F009_ep2d_diff_3scan_trace_p2_20150110171319a.nii"
```
Then I realize the error in the conversion from dcm2niix,
```
Slice positions repeated, but number of slices (4508) not divisible by number of repeats (105): missing images?
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 105 times
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.
```
However, dcm2niix continues and if I now run dcm2bids again I got the rigth images and bad images are ignored, as I think it should be. Is there any way that dcm2bids could ignore errors from dcm2niix and continue?

**Comment by neurolabusc** [comment]
1. dcm2niix will finish with a non-zero exit status. This is because of the series that generated the "4508 is not divisible by 105". You can see this by running `echo $?` after the dcm2niix command line argument. I would suggest any software terminate in these situations to allow a human to resolve the error. So while you are strictly correct that dcm2niix continues after this series, it reports a catastrophic error to any tool that has called it.
2. I would try to resolve this by renaming (`-r y`) your DICOMs so that each series is in a different folder, and then inspecting the series with 4508 DICOM files: `$ dcm2niix -r y - -o /nas/data/facehbi/bids/ /nas/corachan/facehbi//F009/`. If only slices from the last volume are missing you can remove the excess slices. I would check the history of these images to determine what happened.
3. It looks like you are using a Siemens system. In future, if you are using an XA system you should export as enhanced mode, otherwise set your EPI sequences to save as mosaics. This will be faster, create fewer files, require less disk space, and eliminate the partial volume problems.
4. For future acquisitions, I would uncheck the option in the diffusion tab to create derived images (FA, Trace, etc). You can create better derived images after processing (degibbs, denoise, eddy, Topup) and you will avoid the Siemens bug where these files are created without Image Orientation Patient [0020,0037](http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,0037)) - this is a type 1 attribute so these are not valid DICOM images. Again, this will save disk space, processing time, etc.
5. For import to BIDS, I would run dcm2niix with `-i y`: this should ignore derived images and localizer scouts, and therefore dramatically reduce the warning messages.

**Comment by asqwerty666** [comment]
Thanks very much.Your answer has been helpful. I realize now that I can run dcm2niix first with whatever options I need and then run dcm2bids to organize my images. The timing will be the same.
On the other hand, I don't have too much control in the acquisition of images but I will share your suggestions with my provider. I'm sure that we can arrange something to improve the acquisition.

**Comment by kousu** [comment]
I stumbled backwards into some of the same concerns in #100.

**Comment by arnaudbore** [comment]
Dear @asqwerty666 ,

We are moving forward with a [2021 initiative](https://github.com/UNFmontreal/Dcm2Bids/issues/108) and we would like if you can share your experience and what would you improve.

Have a good day
