### ISSUE TITLE
Bizarre python error - ModuleNotFoundError: No module named 'dcm2bids.scaffold'

### ISSUE THREAD

**Issue by richardbeare** [UNFmontreal/Dcm2Bids#76]
Hi,
I had assumed that my miniconda installation was corrupted somehow, but I get the same error in a fresh singularity container when attempting to run dcm2bids after installing from a fresh github clone:

```bash
# setup a singularity container - s.def attached as s.txt
sudo singularity build --sandbox ub/ s.def
```

```bash
$ git clone https://github.com/cbedetti/Dcm2Bids.git
Cloning into 'Dcm2Bids'...
remote: Enumerating objects: 1046, done.
remote: Total 1046 (delta 0), reused 0 (delta 0), pack-reused 1046
Receiving objects: 100% (1046/1046), 526.28 KiB | 697.00 KiB/s, done.
Resolving deltas: 100% (591/591), done.
$ sudo singularity shell --writable ub/
Singularity ub:/tmp> cd Dcm2Bids/
Singularity ub:/tmp/Dcm2Bids> python3 setup.py build  
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running build
running build_py
creating build
creating build/lib
creating build/lib/dcm2bids
copying dcm2bids/structure.py -> build/lib/dcm2bids
copying dcm2bids/dcm2niix.py -> build/lib/dcm2bids
copying dcm2bids/helper.py -> build/lib/dcm2bids
copying dcm2bids/logger.py -> build/lib/dcm2bids
copying dcm2bids/utils.py -> build/lib/dcm2bids
copying dcm2bids/__init__.py -> build/lib/dcm2bids
copying dcm2bids/dcm2bids.py -> build/lib/dcm2bids
copying dcm2bids/version.py -> build/lib/dcm2bids
copying dcm2bids/sidecar.py -> build/lib/dcm2bids
Singularity ub:/tmp/Dcm2Bids> python3 setup.py install
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating dcm2bids.egg-info
writing dcm2bids.egg-info/PKG-INFO
writing dependency_links to dcm2bids.egg-info/dependency_links.txt
writing entry points to dcm2bids.egg-info/entry_points.txt
writing requirements to dcm2bids.egg-info/requires.txt
writing top-level names to dcm2bids.egg-info/top_level.txt
writing manifest file 'dcm2bids.egg-info/SOURCES.txt'
reading manifest file 'dcm2bids.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dcm2bids.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/structure.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/dcm2niix.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/helper.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/logger.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/utils.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/__init__.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/dcm2bids.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/version.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/sidecar.py -> build/bdist.linux-x86_64/egg/dcm2bids
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/structure.py to structure.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/dcm2niix.py to dcm2niix.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/helper.py to helper.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/logger.py to logger.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/dcm2bids.py to dcm2bids.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/sidecar.py to sidecar.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/dcm2bids-2.1.4-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dcm2bids-2.1.4-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/dcm2bids-2.1.4-py3.6.egg
Copying dcm2bids-2.1.4-py3.6.egg to /usr/local/lib/python3.6/dist-packages
dcm2bids 2.1.4 is already the active version in easy-install.pth
Installing dcm2bids script to /usr/local/bin
Installing dcm2bids_helper script to /usr/local/bin
Installing dcm2bids_scaffold script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/dcm2bids-2.1.4-py3.6.egg
Processing dependencies for dcm2bids==2.1.4
Searching for future==0.18.2
Best match: future 0.18.2
Processing future-0.18.2-py3.6.egg
future 0.18.2 is already the active version in easy-install.pth
Installing futurize script to /usr/local/bin
Installing pasteurize script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages/future-0.18.2-py3.6.egg
Finished processing dependencies for dcm2bids==2.1.4
Singularity ub:/tmp/Dcm2Bids> dcm2bids
Traceback (most recent call last):
  File "/usr/local/bin/dcm2bids", line 11, in <module>
    load_entry_point('dcm2bids==2.1.4', 'console_scripts', 'dcm2bids')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/dcm2bids-2.1.4-py3.6.egg/dcm2bids/__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'dcm2bids.scaffold'
Singularity ub:/tmp/Dcm2Bids> 

```
[s.txt](https://github.com/cbedetti/Dcm2Bids/files/4170421/s.txt)

**Comment by kousu** [comment]
I'm seeing this too, on ArchLinux with the distro python 3.8.3.

```
$ git clone https://github.com/cbedetti/Dcm2Bids
Cloning into 'Dcm2Bids'...
remote: Enumerating objects: 1046, done.
remote: Total 1046 (delta 0), reused 0 (delta 0), pack-reused 1046
Receiving objects: 100% (1046/1046), 526.28 KiB | 1.83 MiB/s, done.
Resolving deltas: 100% (591/591), done.
$ cd Dcm2Bids/
$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating dcm2bids.egg-info
writing dcm2bids.egg-info/PKG-INFO
writing dependency_links to dcm2bids.egg-info/dependency_links.txt
writing entry points to dcm2bids.egg-info/entry_points.txt
writing requirements to dcm2bids.egg-info/requires.txt
writing top-level names to dcm2bids.egg-info/top_level.txt
writing manifest file 'dcm2bids.egg-info/SOURCES.txt'
reading manifest file 'dcm2bids.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dcm2bids.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dcm2bids
copying dcm2bids/structure.py -> build/lib/dcm2bids
copying dcm2bids/__init__.py -> build/lib/dcm2bids
copying dcm2bids/helper.py -> build/lib/dcm2bids
copying dcm2bids/dcm2niix.py -> build/lib/dcm2bids
copying dcm2bids/utils.py -> build/lib/dcm2bids
copying dcm2bids/dcm2bids.py -> build/lib/dcm2bids
copying dcm2bids/sidecar.py -> build/lib/dcm2bids
copying dcm2bids/logger.py -> build/lib/dcm2bids
copying dcm2bids/version.py -> build/lib/dcm2bids
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/structure.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/__init__.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/helper.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/dcm2niix.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/utils.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/dcm2bids.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/sidecar.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/logger.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/version.py -> build/bdist.linux-x86_64/egg/dcm2bids
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/structure.py to structure.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/helper.py to helper.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/dcm2niix.py to dcm2niix.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/utils.py to utils.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/dcm2bids.py to dcm2bids.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/sidecar.py to sidecar.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/logger.py to logger.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/dcm2bids/version.py to version.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/dcm2bids-2.1.4-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dcm2bids-2.1.4-py3.8.egg
Removing /usr/lib/python3.8/site-packages/dcm2bids-2.1.4-py3.8.egg
Copying dcm2bids-2.1.4-py3.8.egg to /usr/lib/python3.8/site-packages
dcm2bids 2.1.4 is already the active version in easy-install.pth
Installing dcm2bids script to /usr/bin
Installing dcm2bids_helper script to /usr/bin
Installing dcm2bids_scaffold script to /usr/bin

Installed /usr/lib/python3.8/site-packages/dcm2bids-2.1.4-py3.8.egg
Processing dependencies for dcm2bids==2.1.4
Searching for future==0.18.2
Best match: future 0.18.2
Adding future 0.18.2 to easy-install.pth file
Installing futurize script to /usr/bin
Installing pasteurize script to /usr/bin

Using /usr/lib/python3.8/site-packages
Finished processing dependencies for dcm2bids==2.1.4
$ which dcm2bids
/usr/bin/dcm2bids
[kousu@requiem Dcm2Bids]$ /usr/bin/dcm2bids
Traceback (most recent call last):
  File "/usr/bin/dcm2bids", line 11, in <module>
    load_entry_point('dcm2bids==2.1.4', 'console_scripts', 'dcm2bids')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/lib/python3.8/site-packages/dcm2bids-2.1.4-py3.8.egg/dcm2bids/__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'dcm2bids.scaffold'
```

with a virtualenv:

```
$ python3 -m virtualenv .venv
created virtual environment CPython3.8.3.final.0-64 in 905ms
  creator CPython3Posix(dest=/home/kousu/src/neuropoly/Dcm2Bids/.venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/kousu/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . .venv/bin/activate
(.venv) $ python setup.py install
running install
running bdist_egg
running egg_info
creating dcm2bids.egg-info
writing dcm2bids.egg-info/PKG-INFO
writing dependency_links to dcm2bids.egg-info/dependency_links.txt
writing entry points to dcm2bids.egg-info/entry_points.txt
writing requirements to dcm2bids.egg-info/requires.txt
writing top-level names to dcm2bids.egg-info/top_level.txt
writing manifest file 'dcm2bids.egg-info/SOURCES.txt'
reading manifest file 'dcm2bids.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dcm2bids.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dcm2bids
copying dcm2bids/structure.py -> build/lib/dcm2bids
copying dcm2bids/__init__.py -> build/lib/dcm2bids
copying dcm2bids/helper.py -> build/lib/dcm2bids
copying dcm2bids/dcm2niix.py -> build/lib/dcm2bids
copying dcm2bids/utils.py -> build/lib/dcm2bids
copying dcm2bids/dcm2bids.py -> build/lib/dcm2bids
copying dcm2bids/sidecar.py -> build/lib/dcm2bids
copying dcm2bids/logger.py -> build/lib/dcm2bids
copying dcm2bids/version.py -> build/lib/dcm2bids
warning: build_py: byte-compiling is disabled, skipping.

creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/structure.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/__init__.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/helper.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/dcm2niix.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/utils.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/dcm2bids.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/sidecar.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/logger.py -> build/bdist.linux-x86_64/egg/dcm2bids
copying build/lib/dcm2bids/version.py -> build/bdist.linux-x86_64/egg/dcm2bids
warning: install_lib: byte-compiling is disabled, skipping.

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dcm2bids.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/dcm2bids-2.1.4-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dcm2bids-2.1.4-py3.8.egg
Copying dcm2bids-2.1.4-py3.8.egg to /home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages
Adding dcm2bids 2.1.4 to easy-install.pth file
Installing dcm2bids script to /home/kousu/src/neuropoly/Dcm2Bids/.venv/bin
Installing dcm2bids_helper script to /home/kousu/src/neuropoly/Dcm2Bids/.venv/bin
Installing dcm2bids_scaffold script to /home/kousu/src/neuropoly/Dcm2Bids/.venv/bin

Installed /home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/dcm2bids-2.1.4-py3.8.egg
Processing dependencies for dcm2bids==2.1.4
Searching for future>=0.17.1
Reading https://pypi.org/simple/future/
Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz#sha256=b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d
Best match: future 0.18.2
Processing future-0.18.2.tar.gz
Writing /tmp/easy_install-eq2f77gv/future-0.18.2/setup.cfg
Running future-0.18.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eq2f77gv/future-0.18.2/egg-dist-tmp-8xaz8awi
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

zip_safe flag not set; analyzing archive contents...
Moving future-0.18.2-py3.8.egg to /home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages
Adding future 0.18.2 to easy-install.pth file
Installing futurize script to /home/kousu/src/neuropoly/Dcm2Bids/.venv/bin
Installing pasteurize script to /home/kousu/src/neuropoly/Dcm2Bids/.venv/bin

Installed /home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/future-0.18.2-py3.8.egg
Finished processing dependencies for dcm2bids==2.1.4
(.venv) $ which dcm2bids
/home/kousu/src/neuropoly/Dcm2Bids/.venv/bin/dcm2bids
(.venv) $ dcm2bids
Traceback (most recent call last):
  File "/home/kousu/src/neuropoly/Dcm2Bids/.venv/bin/dcm2bids", line 11, in <module>
    load_entry_point('dcm2bids==2.1.4', 'console_scripts', 'dcm2bids')()
  File "/home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2453, in load
    return self.resolve()
  File "/home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2459, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/home/kousu/src/neuropoly/Dcm2Bids/.venv/lib/python3.8/site-packages/dcm2bids-2.1.4-py3.8.egg/dcm2bids/__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'dcm2bids.scaffold'
```
